### ISSUE TITLE
[Feat] 다이어리 controller 계층 테스트 코드 작성

### ISSUE THREAD

**Issue by hyeonji91** [Namo-log/Server#119]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

 다이어리 controller 계층 테스트 코드 작성

## **Todo**

- [ ] 기록 생성
- [ ] 일정 기록 월간 조회
- [ ] 개인 일정 기록 전체 조회
- [ ] 일정 기록 개별 조회
- [ ] 일정 기록 수정
- [ ] 일정 기록 삭제
