### ISSUE TITLE
[Feat] 모임 메모 Validation 검증 로직 및 비기능 개발

### ISSUE THREAD

**Issue by galug** [Namo-log/Server#50]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Refactor : 코드 리팩토링 작업

## **Description**

형식적 혹은 논리적 validation 이 필요한 지점을 찾고 이에 대한 검증 처리를 해주겠습니다. 

## **Todo**

- [ ] 모임 메모 
  - [ ] 모임 메모 생성: 모임 스케줄에 속한 유저가 모임 메모를 생성하는지 확인 
  - [ ] 모임 메모 수정: 모임 스케줄에 속한 유저가 모임 메모를 수정하는지 확인 
  - [ ] 모임 메모 삭제: 모임 스케줄에 속한 유저가 모임 메모를 삭제하는지 확인
