### ISSUE TITLE
[Feat] 카테고리 Controller 테스트 구축 

### ISSUE THREAD

**Issue by galug** [Namo-log/Server#60]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Test : 테스트 코드 작성 및 테스트 작업

## **Description**

단위 테스트 환경과 통합 테스트 환경을 구축하겠습니다. 

## **Todo**

- [ ] 계층에 따라 테스트 환경을 구축할 것입니다.
- [ ] Controller 계층은 Mock 을 이용한 단위 테스트를 통해 형식적 검증이 잘 동작하는지 확인하겠습니다.
