### ISSUE TITLE
[Feat] 일정 테스트 코드 작성

### ISSUE THREAD

**Issue by hyeonji91** [Namo-log/Server#95]
## Type of change

- [ x ] Feature : 새로운 기능 추가

## **Description**

일정 도메인 테스트 코드 작성

## **Todo**

- [x] controller계층 테스트 코드 작성
- [ ] service계층 테스트 코드 작성
- [ ] repository 계층 테스트 코드 작성
